### ISSUE TITLE
disable checking resource at URI

### ISSUE THREAD

**Issue by chakravarthyvp** [daveclayton/json-schema-validator#214]
Hi,
 
    Is there a way to disable URI referencing. I have ID added as below to uniquely identify this schema however I do not want to publish the schema as the URI referenced. During validation, is there a way to disable validating the URI ?
 
`
{
    "id": "http://some.domain.com/my-schema#"
    "$schema": "http://json-schema.org/schema#",
    "description": "schema for PBA",
     .....
    },
    "definitions": {
    }
   ...
`

> 
Exception in thread "main" com.github.fge.jsonschema.core.exceptions.ProcessingException: fatal: unable to dereference URI "http://some.domain.com/my-schema#"
    level: "fatal"
    uri: "http://some.domain.com/my-schema#"
    exceptionMessage: "http://some.domain.com/my-schema#"

	at com.github.fge.jsonschema.core.load.URIManager.getContent(URIManager.java:115)
	at com.github.fge.jsonschema.core.load.SchemaLoader$1.load(SchemaLoader.java:115)

**Comment by blackr1234** [comment]
Is there any update on this ticket?
Would like to understand why this happens.
